<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lidar_robot">
  <xacro:property name="wheel_len" value=".35521" />
  <xacro:property name="format" value="dae" />

  <xacro:include filename="$(find lidar_robot)/gazebo/base.gazebo" />
  <xacro:include filename="$(find lidar_robot)/gazebo/materials.xacro" />

    <xacro:macro name="wheel" params="wheel_no x y">
        <link name="wheel_${wheel_no}">
            <inertial>
                <origin xyz="2.018E-06 -1.33270000000008E-05 -0.013184" rpy="0 0 0" />
                <mass value="1.4753" />
                <inertia ixx="0.00196296986572325" ixy="-9.36007189523935E-08" ixz="-1.87549956536754E-08" iyy="-3.01353957649888E-07" iyz="-0.0019629938784401" izz="3.01353957650166E-07" />
            </inertial>
            <visual>
                <geometry>
                    <mesh filename="package://lidar_robot/meshes/wheel.${format}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="aluminium">
                    <color rgba="0.79216 0.81961 0.93333 1" />
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.5707963267949 0 0" />
                <geometry>
                    <mesh filename="package://lidar_robot/meshes/wheel.${format}" />
                </geometry>
            </collision>
        </link>
        <joint name="base_to_wheel_${wheel_no}" type="continuous">
            <axis xyz="0 1 0" />
            <parent link="base_link" />
            <child link="wheel_${wheel_no}" />
            <origin xyz="${x*wheel_len} ${y*wheel_len} 0" rpy="0 0 ${((pi/2) * -x) + (-((pi/2)*(y-1))*y)}" />
	    <dynamics damping="0.7"/>
        </joint>
	  <transmission name="tran_w_${wheel_no}">
	    <type>transmission_interface/SimpleTransmission</type>
	    <joint name="base_to_wheel_${wheel_no}">
              <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor_w_${wheel_no}">
              <hardwareInterface>EffortJointInterface</hardwareInterface>
              <mechanicalReduction>1</mechanicalReduction>
            </actuator>
          </transmission>
    </xacro:macro>

    <link name="base_link">
        <inertial>
            <origin xyz="-0.0099877 -7.87679999999704E-06 0.048337" rpy="0 0 0" />
            <mass value="6.0202" />
            <inertia ixx="0.193404669051707" ixy="-1.57451867364915E-06" ixz="7.52537384896092E-06" iyy="1.01182032486468E-06" iyz="-0.193412304186565" izz="-1.01182032483072E-06" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="1.5707963267949 0 0" />
            <geometry>
                <mesh filename="package://lidar_robot/meshes/base.stl" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 0.7" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <mesh filename="package://lidar_robot/meshes/base.stl" />
            </geometry>
        </collision>
    </link>

    <xacro:wheel wheel_no="1" x="0" y="1" />
    <xacro:wheel wheel_no="2" x="-1" y="0" />
    <xacro:wheel wheel_no="3" x="0" y="-1" />
    <xacro:wheel wheel_no="4" x="1" y="0" />

  <link name="rplidar">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://lidar_robot/meshes/rplidar.stl"/>
      </geometry>
      <material name="">
                <color rgba="0.1 0.1 0.1 1" />
      </material>
    </visual>
    <inertial>
      <origin xyz="0.010606 0.000652570000000001 0.015976" rpy="0 0 0" />
      <mass value="0.095964" />
      <inertia ixx="4.20678723401718E-05" ixy="-1.30097836316357E-05" ixz="4.33129403884459E-07" iyy="1.48659304158389E-06" iyz="-7.76207439662319E-05" izz="-1.48659304158388E-06" />
    </inertial>
  </link>
  <joint name="rplidar_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <child link="rplidar"/>
    <parent link="base_link"/>
  </joint>

  <link name="x">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="">
        <color rgba="1 0 0 0.3" />
      </material>
    </visual>
  </link>
  <joint name="x_joint" type="fixed">
    <origin xyz="1 0 0" rpy="0 0 0"/>
    <child link="x"/>
    <parent link="base_link"/>
  </joint>

  <link name="y">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="">
        <color rgba="0 1 0 0.3" />
      </material>
    </visual>
  </link>
  <joint name="y_joint" type="fixed">
    <origin xyz="0 1 0" rpy="0 0 0"/>
    <child link="y"/>
    <parent link="base_link"/>
  </joint>

</robot>
